<a href="https://colab.research.google.com/github/vishkaush/misc-projects/blob/main/Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python-Numpy Vectors vs Rank 1 Arrays

In [1]:
import numpy as np

a = np.random.randn(5) # creates 5 random Gaussian numbers
print("a= ", a)
print("a's shape = ", a.shape) # rank 1 array - neither row vector, nor column vector
print("a transpose = ", a.T) # remains the same!
print("a dot a transpose = ", np.dot(a,a.T)) # you expect a 5X5 matrix, but you get a real number!
# fix this by explicitly making it a column vector or a row vector like so:
a = a.reshape((1,5))
print("reshaped a = ", a)
print("shape of reshaped a = ", a.shape)

a=  [ 1.12212486  0.29191375  0.48777776 -1.25455834  0.27985007]
a's shape =  (5,)
a transpose =  [ 1.12212486  0.29191375  0.48777776 -1.25455834  0.27985007]
a dot a transpose =  3.2345376856988937
reshaped a =  [[ 1.12212486  0.29191375  0.48777776 -1.25455834  0.27985007]]
shape of reshaped a =  (1, 5)


In [2]:
# Hence, better to mention the dimensions explicitly even for vectors, i.e. treat vectors as matrices
a = np.random.randn(5,1)
print("a = ", a)
print("a's shape = ", a.shape) 
print("a transpose = ", a.T) 
prod = np.dot(a,a.T)
print("a dot a transpose = ", prod) 
assert(prod.shape == (5,5))  # good practice to do a sanity check of dimensions

a =  [[-0.20276811]
 [-0.05710923]
 [ 0.3410439 ]
 [ 0.51929858]
 [ 0.53560152]]
a's shape =  (5, 1)
a transpose =  [[-0.20276811 -0.05710923  0.3410439   0.51929858  0.53560152]]
a dor a transpose =  [[ 0.04111491  0.01157993 -0.06915283 -0.10529719 -0.10860291]
 [ 0.01157993  0.00326146 -0.01947675 -0.02965674 -0.03058779]
 [-0.06915283 -0.01947675  0.11631094  0.17710361  0.18266363]
 [-0.10529719 -0.02965674  0.17710361  0.26967102  0.27813711]
 [-0.10860291 -0.03058779  0.18266363  0.27813711  0.28686899]]


# Benefits of Vectorization

## Dot Product

In [15]:
import numpy as np
import math
a = np.random.rand(1000000)
b = np.random.rand(1000000)
%time c=np.dot(a,b)
print("Dot product = ", c)

CPU times: user 2.71 ms, sys: 1.11 ms, total: 3.83 ms
Wall time: 5.48 ms
Dot product =  250185.55851631792


In [5]:
%%time
c = 0
for i in range(1000000):
  c += a[i]*b[i]

CPU times: user 567 ms, sys: 1.85 ms, total: 569 ms
Wall time: 570 ms


In [6]:
print("Dot product = ", c)

Dot product =  250163.49888724205


## Product of Matrix and Vector

In [12]:
A = np.random.rand(1000,1000)
v = np.random.rand(1000)
u = np.zeros((1000, 1))

In [11]:
%%time
for i in range(1000):
  for j in range(1000):
    u[i] += A[i][j]*v[j]

CPU times: user 3.26 s, sys: 0 ns, total: 3.26 s
Wall time: 3.27 s


In [13]:
%%time
u = np.dot(A,v)

CPU times: user 790 µs, sys: 1.95 ms, total: 2.74 ms
Wall time: 2.18 ms


## Exponent

In [16]:
%%time
u = np.zeros((1000,1))
for i in range(1000):
  u[i]=math.exp(v[i])

CPU times: user 1.09 ms, sys: 0 ns, total: 1.09 ms
Wall time: 1.13 ms


In [17]:
%%time
u = np.exp(v)

CPU times: user 84 µs, sys: 0 ns, total: 84 µs
Wall time: 122 µs


# Sum

In [3]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("A = ", A)
print("A's shape = ", A.shape)
sumHorizontally = A.sum(axis=1)
print("After horizontal sum = ", sumHorizontally)
print("Shape after horizontal sum = ", sumHorizontally.shape)
sumVertically = A.sum(axis=0)
print("After vertical sum = ", sumVertically)
print("Shape after vertical sum = ", sumVertically.shape)

A =  [[1 2 3]
 [4 5 6]
 [7 8 9]]
A's shape =  (3, 3)
After horizontal sum =  [ 6 15 24]
Shape after horizontal sum =  (3,)
After vertical sum =  [12 15 18]
Shape after vertical sum =  (3,)
