<a href="https://colab.research.google.com/github/vishkaush/misc-projects/blob/main/Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python-Numpy Vectors vs Rank 1 Arrays

In [ ]:
import numpy as np

a = np.random.randn(5) # creates 5 random Gaussian numbers
print("a= ", a)
print("a's shape = ", a.shape) # rank 1 array - neither row vector, nor column vector
print("a transpose = ", a.T) # remains the same!
print("a dot a transpose = ", np.dot(a,a.T)) # you expect a 5X5 matrix, but you get a real number!
# fix this by explicitly making it a column vector or a row vector like so:
a = a.reshape((1,5))
print("reshaped a = ", a)
print("shape of reshaped a = ", a.shape)

a=  [ 1.12212486  0.29191375  0.48777776 -1.25455834  0.27985007]
a's shape =  (5,)
a transpose =  [ 1.12212486  0.29191375  0.48777776 -1.25455834  0.27985007]
a dot a transpose =  3.2345376856988937
reshaped a =  [[ 1.12212486  0.29191375  0.48777776 -1.25455834  0.27985007]]
shape of reshaped a =  (1, 5)


In [ ]:
# Hence, better to mention the dimensions explicitly even for vectors, i.e. treat vectors as matrices
a = np.random.randn(5,1)
print("a = ", a)
print("a's shape = ", a.shape) 
print("a transpose = ", a.T) 
prod = np.dot(a,a.T)
print("a dot a transpose = ", prod) 
assert(prod.shape == (5,5))  # good practice to do a sanity check of dimensions

a =  [[-0.20276811]
 [-0.05710923]
 [ 0.3410439 ]
 [ 0.51929858]
 [ 0.53560152]]
a's shape =  (5, 1)
a transpose =  [[-0.20276811 -0.05710923  0.3410439   0.51929858  0.53560152]]
a dor a transpose =  [[ 0.04111491  0.01157993 -0.06915283 -0.10529719 -0.10860291]
 [ 0.01157993  0.00326146 -0.01947675 -0.02965674 -0.03058779]
 [-0.06915283 -0.01947675  0.11631094  0.17710361  0.18266363]
 [-0.10529719 -0.02965674  0.17710361  0.26967102  0.27813711]
 [-0.10860291 -0.03058779  0.18266363  0.27813711  0.28686899]]


# Benefits of Vectorization

## Dot (Inner) Product

In [ ]:
import numpy as np
import math
a = np.random.rand(100)
b = np.random.rand(100)
%time c=np.dot(a,b)
print("Dot product = ", c)

CPU times: user 22 µs, sys: 0 ns, total: 22 µs
Wall time: 26.5 µs
Dot product =  22.142277202972636


In [ ]:
%%time
c = 0
for i in range(len(a)):
  c += a[i]*b[i]

CPU times: user 66 µs, sys: 17 µs, total: 83 µs
Wall time: 84.9 µs


In [ ]:
print("Dot product = ", c)

Dot product =  22.14227720297264


## Outer Product

In [ ]:
%%time
outer = np.zeros((len(a),len(b)))
for i in range(len(a)):
    for j in range(len(b)):
        outer[i,j] = a[i]*b[j]

CPU times: user 10.3 ms, sys: 0 ns, total: 10.3 ms
Wall time: 10.8 ms


In [ ]:
%time outer = np.outer(a,b)

CPU times: user 152 µs, sys: 0 ns, total: 152 µs
Wall time: 157 µs


## ELement-wise multiplication

In [ ]:
%%time
mul = np.zeros(len(a))
for i in range(len(a)):
    mul[i] = a[i]*b[i]

CPU times: user 0 ns, sys: 133 µs, total: 133 µs
Wall time: 156 µs


In [ ]:
%time mul = np.multiply(a,b)

CPU times: user 36 µs, sys: 6 µs, total: 42 µs
Wall time: 55.6 µs


## Product of Matrix and Vector

In [ ]:
A = np.random.rand(1000,1000)
v = np.random.rand(1000)
u = np.zeros((1000, 1))

In [ ]:
%%time
for i in range(1000):
  for j in range(1000):
    u[i] += A[i][j]*v[j]

CPU times: user 3.59 s, sys: 0 ns, total: 3.59 s
Wall time: 3.6 s


In [ ]:
%%time
u = np.dot(A,v)  # np.dot is used for matrix-matrix and matrix-vector multiplication

CPU times: user 5.32 ms, sys: 0 ns, total: 5.32 ms
Wall time: 4.73 ms


## Exponent

In [ ]:
%%time
u = np.zeros((1000,1))
for i in range(1000):
  u[i]=math.exp(v[i])

CPU times: user 1.07 ms, sys: 0 ns, total: 1.07 ms
Wall time: 1.13 ms


In [ ]:
%%time
u = np.exp(v)

CPU times: user 70 µs, sys: 0 ns, total: 70 µs
Wall time: 74.1 µs


# Sum

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("A = ", A)
print("A's shape = ", A.shape)
sumHorizontally = A.sum(axis=1, keepdims=True)
print("After horizontal sum (preserving dimensions)= ", sumHorizontally)
print("Shape after horizontal sum = ", sumHorizontally.shape)
sumVertically = A.sum(axis=0)
print("After vertical sum = ", sumVertically)
print("Shape after vertical sum = ", sumVertically.shape)

A =  [[1 2 3]
 [4 5 6]
 [7 8 9]]
A's shape =  (3, 3)
After horizontal sum (preserving dimensions)=  [[ 6]
 [15]
 [24]]
Shape after horizontal sum =  (3, 1)
After vertical sum =  [12 15 18]
Shape after vertical sum =  (3,)


# Generating a sequence of numbers

In [ ]:
# only integral
for i in range(1, 10, 2):
  print(i, end=", ")

1, 3, 5, 7, 9, 

In [ ]:
[x * 0.1 for x in range(0, 10)]

[0.0,
 0.1,
 0.2,
 0.30000000000000004,
 0.4,
 0.5,
 0.6000000000000001,
 0.7000000000000001,
 0.8,
 0.9]

In [ ]:
import numpy as np
np.arange(1, 2, 0.1) # same as scipy.arange

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [ ]:
np.arange(1, 1.3, 0.1) # should produce three numbers, but produces 4 due to floating point round off error

array([1. , 1.1, 1.2, 1.3])

In [ ]:
# preferred and more accurate approach
np.linspace(1, 2, 10)


array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])