<a href="https://colab.research.google.com/github/vishkaush/misc-projects/blob/main/Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python-Numpy Vectors vs Rank 1 Arrays

In [35]:
import numpy as np

a = np.random.randn(5) # creates 5 random Gaussian numbers
print(a)
print(a.shape) # rank 1 array - neither row vector, nor column vector
print(a.T) # remains the same!
print(np.dot(a,a.T)) # you expect a 5X5 matrix, but you get a real number!
# fix this by explicitly making it a column vector or a row vector like so:
a = a.reshape((1,5))
print(a)
print(a.shape)

[ 1.26995487 -1.37511047 -0.27478235 -1.18064551 -0.65434548]
(5,)
[ 1.26995487 -1.37511047 -0.27478235 -1.18064551 -0.65434548]
5.4013113546693265
[[ 1.26995487 -1.37511047 -0.27478235 -1.18064551 -0.65434548]]
(1, 5)


In [34]:
# Hence, better to mention the dimensions explicitly even for vectors, i.e. treat vectors as matrices
a = np.random.randn(5,1)
print(a)
print(a.shape) 
print(a.T) 
prod = np.dot(a,a.T)
print(prod) 
assert(prod.shape == (5,5))  # good practice to do a sanity check of dimensions

[[0.00231313]
 [0.41684812]
 [1.32975425]
 [1.35505502]
 [0.76525001]]
(5, 1)
[[0.00231313 0.41684812 1.32975425 1.35505502 0.76525001]]
[[5.35059132e-06 9.64225775e-04 3.07590045e-03 3.13442455e-03
  1.77012622e-03]
 [9.64225775e-04 1.73762354e-01 5.54305556e-01 5.64852136e-01
  3.18993027e-01]
 [3.07590045e-03 5.54305556e-01 1.76824635e+00 1.80189017e+00
  1.01759445e+00]
 [3.13442455e-03 5.64852136e-01 1.80189017e+00 1.83617411e+00
  1.03695587e+00]
 [1.77012622e-03 3.18993027e-01 1.01759445e+00 1.03695587e+00
  5.85607577e-01]]


# Benefits of Vectorization

## Dot Product

In [15]:
import numpy as np
import math
a = np.random.rand(1000000)
b = np.random.rand(1000000)
%time c=np.dot(a,b)
print("Dot product = ", c)

CPU times: user 2.71 ms, sys: 1.11 ms, total: 3.83 ms
Wall time: 5.48 ms
Dot product =  250185.55851631792


In [5]:
%%time
c = 0
for i in range(1000000):
  c += a[i]*b[i]

CPU times: user 567 ms, sys: 1.85 ms, total: 569 ms
Wall time: 570 ms


In [6]:
print("Dot product = ", c)

Dot product =  250163.49888724205


## Product of Matrix and Vector

In [12]:
A = np.random.rand(1000,1000)
v = np.random.rand(1000)
u = np.zeros((1000, 1))

In [11]:
%%time
for i in range(1000):
  for j in range(1000):
    u[i] += A[i][j]*v[j]

CPU times: user 3.26 s, sys: 0 ns, total: 3.26 s
Wall time: 3.27 s


In [13]:
%%time
u = np.dot(A,v)

CPU times: user 790 µs, sys: 1.95 ms, total: 2.74 ms
Wall time: 2.18 ms


## Exponent

In [16]:
%%time
u = np.zeros((1000,1))
for i in range(1000):
  u[i]=math.exp(v[i])

CPU times: user 1.09 ms, sys: 0 ns, total: 1.09 ms
Wall time: 1.13 ms


In [17]:
%%time
u = np.exp(v)

CPU times: user 84 µs, sys: 0 ns, total: 84 µs
Wall time: 122 µs


# Sum

In [26]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)
print(A.shape)
sumHorizontally = A.sum(axis=1)
print(sumHorizontally)
print(sumHorizontally.shape)
sumVertically = A.sum(axis=0)
print(sumVertically)
print(sumVertically.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
[ 6 15 24]
(3,)
[12 15 18]
(3,)
